// [emoji, name, tier (core = 80/20 for ML), explanation, topic list, [[question, answer], ...]]
const TOPICS=[
["🔢","Basic Arithmetic & Number Skills","core","Everything starts here. Order of operations: brackets, powers, multiply/divide, then add/subtract. Fast mental maths saves time in every other topic.","Add, subtract, multiply, divide · BODMAS/PEMDAS · Negative numbers · Place value · Rounding · Estimation · Factors & multiples · Primes · Prime factorization · Divisibility · GCF/HCF · LCM · Arithmetic sequences",[["Calculate 3 + 4 × 2","11 (multiply first)"],["Prime factorization of 36","2² × 3²"],["GCF of 12 and 18","6"]]],
["🍕","Fractions, Decimals & Percentages","core","Fractions, decimals and percentages are three ways to write 'part of a whole'. ML uses them for accuracy scores and probabilities.","Fractions (proper, improper, mixed) · Equivalent & simplifying · Add/subtract/multiply/divide fractions · Decimals · Fraction ↔ decimal · Percentages · % change · Ratios · Proportions · Rates",[["1/2 + 1/3 = ?","5/6"],["Increase 80 by 25%","100"],["Share 40 in the ratio 3:5. Bigger part?","25"]]],
["🔤","Algebra","core","Algebra uses letters for unknown numbers. Golden rule: whatever you do to one side of an equation, do to the other side. ML models are just algebra with many letters.","Variables, constants, coefficients, terms · Expressions · Equations & inequalities · Expanding & factorising · Linear equations · Simultaneous equations · Substitution · Rearranging formulas · Exponents & roots · Scientific notation · Quadratics · Cubics",[["Solve 3x + 5 = 20","x = 5"],["Factorise x² + 5x + 6","(x + 2)(x + 3)"],["Solve x + y = 10 and x − y = 2","x = 6, y = 4"]]],
["📈","Coordinates & Graphs","core","A graph shows a rule as a picture. The slope tells how fast y changes when x goes up by 1. Slope is the seed of the derivative.","Axes & origin · Plotting points · Gradient/slope · Intercepts · Distance & midpoint · Equation of a line · Quadratic, cubic, exponential, log graphs · Graph transformations",[["Slope through (1,2) and (3,6)","(6−2)/(3−1) = 2"],["Midpoint of (2,4) and (8,10)","(5, 7)"],["Distance from (0,0) to (3,4)","5"]]],
["📐","Geometry","useful","Geometry is about shapes, size and space. Pythagoras (a² + b² = c²) gives distance, which ML uses to find similar data points.","Angles · Parallel & perpendicular lines · Triangles · Quadrilaterals · Polygons · Circles, chords, arcs, sectors, tangents · Symmetry · Congruence & similarity · Pythagoras · Perimeter, area, surface area, volume",[["Right triangle with legs 6 and 8. Hypotenuse?","10"],["Area of a circle with r = 3","9π ≈ 28.3"],["Angles in a triangle add up to?","180°"]]],
["📏","Trigonometry","useful","Trig links angles and side lengths. Sin and cos make waves, used in signals, audio and rotations.","Sin, cos, tan · SOH-CAH-TOA · Sine & cosine rules · Identities · Radians · Unit circle · Trig graphs · Inverse trig (sin⁻¹, cos⁻¹, tan⁻¹)",[["sin 30° = ?","0.5"],["Opposite = 3, hypotenuse = 5. sin θ = ?","0.6"],["180° in radians","π"]]],
["∞","Powers, Roots & Logarithms","core","An exponent means repeated multiplication. A log is the opposite of an exponent. Logs turn hard multiplications into easy additions, and ML loss functions use them a lot.","Powers · Negative & fractional exponents · Square & cube roots · Surds · Exponential functions · log & ln · Laws of indices · Laws of logarithms",[["2⁻³ = ?","1/8"],["log₂ 32 = ?","5"],["ln(e²) = ?","2"]]],
["∫","Calculus","core","Calculus studies change. Derivative = slope at one point. Integral = area under a curve. Gradients (derivatives with many variables) are how neural networks learn.","Limits · Continuity · Derivatives · Power, chain, product, quotient rules · Implicit differentiation · Higher derivatives · Tangent lines · Optimization · Integrals (definite & indefinite) · Fundamental theorem · Area under curves · Volumes of revolution · Partial derivatives",[["d/dx of 5x⁴","20x³"],["∫ 2x dx","x² + C"],["d/dx of (3x² + 1)³ (chain rule)","18x(3x² + 1)²"]]],
["🎲","Probability","core","Probability measures how likely something is, from 0 (never) to 1 (always). ML models often output probabilities. Learn Bayes' rule well.","Outcomes & sample space · Experimental vs theoretical · Complement · Independent & dependent events · Conditional probability & Bayes · Probability trees · Permutations & combinations · Expected value · Random variables · Binomial & normal distributions",[["P(at least one head in 2 coin flips)","3/4"],["P(A|B) if P(A and B) = 0.2 and P(B) = 0.5","0.4"],["Expected value of one fair die roll","3.5"]]],
["📊","Statistics","core","Statistics learns from data. Mean, variance and standard deviation describe data. Correlation and regression find patterns. This is the heart of data science.","Population & sample · Mean, median, mode, range · Variance & standard deviation · Quartiles, percentiles, IQR · Tables, histograms, scatter, box plots · Correlation · Regression · Sampling · Inference",[["Median of 3, 9, 1, 7, 5","5"],["Variance of 2,4,4,4,5,5,7,9","4 (mean 5)"],["Does correlation prove causation?","No"]]],
["🧮","Matrices","core","A matrix is a table of numbers. Multiplying matrices is how a neural network layer changes data. Learn multiplication and transpose first.","Add/subtract · Scalar multiplication · Matrix multiplication · Identity & zero matrix · Transpose · Determinant · Inverse · Solving systems · Eigenvalues & eigenvectors",[["[[1,2],[3,4]] + [[1,0],[0,1]]","[[2,2],[3,5]]"],["Determinant of [[2,1],[3,4]]","2·4 − 1·3 = 5"],["Transpose of [[1,2],[3,4]]","[[1,3],[2,4]]"]]],
["🔐","Number Theory","later","Number theory studies whole numbers and their patterns. Modular arithmetic is the base of cryptography and hashing.","Integers, rational, irrational, real numbers · Primes · Modular arithmetic · Divisibility · GCD & LCM · Diophantine equations",[["17 mod 5","2"],["GCD of 48 and 18","6"]]],
["🧠","Logic & Proof","later","Logic and proof show why maths is true. Sets and Venn diagrams are everywhere in data and databases.","Statements · AND/OR/NOT · Implication & if-and-only-if · Sets & Venn diagrams · Direct proof · Proof by contradiction · Induction",[["A = {1,2,3}, B = {3,4}. A ∩ B?","{3}"],["Negation of 'all cats are black'","Some cat is not black"]]],
["🧩","Sequences & Series","useful","A sequence is an ordered list of numbers. A series is their sum. Sigma (Σ) notation is in almost every ML formula.","Arithmetic & geometric sequences · Recursive sequences · Arithmetic & geometric series · Infinite series · Sigma notation Σ · Convergence & divergence",[["10th term of 3, 7, 11, …","39"],["1 + 2 + 3 + … + 100","5050"],["1 + 1/2 + 1/4 + … (forever)","2"]]],
["🌀","Complex Numbers","later","i is a number where i² = −1. Complex numbers help with waves, signals and rotations (Fourier transform).","Imaginary unit i · Real & imaginary parts · a + bi · Complex plane · Conjugates · Modulus & argument · Polar form · Euler's formula",[["i² = ?","−1"],["(2 + 3i) + (1 − i)","3 + 2i"],["|3 + 4i|","5"]]],
["🔺","Vectors","core","A vector has size and direction. In ML, a vector is a list of features about one thing. The dot product measures how similar two vectors are.","Magnitude & direction · Components · Addition · Scalar multiplication · Dot product · Cross product · Unit vectors · 2D & 3D vectors",[["Length of (3, 4)","5"],["(1,2,3) · (4,5,6)","32"],["(2,1) + (−1,3)","(1, 4)"]]],
["⭕","Coordinate & Analytic Geometry","useful","Analytic geometry draws shapes with equations, for example a circle is x² + y² = r².","Distance & midpoint · Lines · Circles · Parabolas · Ellipses · Hyperbolas · Conic sections · 3D coordinates",[["Centre and radius of x² + y² = 25","Centre (0,0), radius 5"],["Distance from (1,1) to (4,5)","5"]]],
["🔄","Transformations","useful","Transformations move or change shapes: slide, turn, flip, resize. Matrices can do all of them, the same idea as image processing.","Translation · Rotation · Reflection · Enlargement · Stretching & shearing · Transformation matrices",[["Reflect (3,2) in the x-axis","(3, −2)"],["Enlarge (2,3) by factor 2 from origin","(4, 6)"]]],
["🎯","Combinatorics","useful","Combinatorics is counting without listing everything. It is needed for probability, passwords and algorithms.","Counting principles · Permutations · Combinations · Factorials · Pascal's triangle · Binomial theorem · Inclusion-exclusion · Pigeonhole principle",[["5! = ?","120"],["C(5,2) = ?","10"],["Ways to arrange 3 of 5 books in order","5·4·3 = 60"]]],
["🧪","Advanced Algebra","later","Advanced algebra studies polynomials and abstract structures (groups, rings, fields). Useful later, rarely needed for ML basics.","Polynomial division · Factor & remainder theorems · Rational functions · Partial fractions · Groups · Rings · Fields",[["Remainder of x² + 1 divided by (x − 2)","5"],["(x² − 1) ÷ (x − 1)","x + 1"]]],
["🌍","Advanced Geometry","later","Geometry beyond flat space: spheres and curved surfaces. Rare in ML, nice for physics and graphics.","Euclidean · Coordinate · Projective · Non-Euclidean · Spherical · Differential geometry",[["Angles of a triangle on a sphere add up to…","More than 180°"],["Which geometries break Euclid's parallel rule?","Spherical and hyperbolic"]]],
["🧬","Linear Algebra","core","Linear algebra is the language of ML: vectors, matrices, eigenvalues. Spend real time here. It is high value.","Vector spaces · Basis & dimension · Linear transformations · Determinants · Eigenvalues & eigenvectors · Orthogonality · Solving linear systems",[["Eigenvalues of [[2,0],[0,3]]","2 and 3"],["Are (1,0) and (0,1) orthogonal?","Yes, dot product = 0"],["Dimension of 3D space","3"]]],
["∂","Advanced Calculus & Analysis","useful","Multivariable calculus extends derivatives to many variables. Gradient, partial derivatives and the chain rule are used in backpropagation.","Real analysis · Differentiability · Multivariable calculus · Partial derivatives · Multiple integrals · Vector calculus · Complex analysis · Fourier series",[["∂/∂x of x²y","2xy"],["Gradient of x² + y² at (1,2)","(2, 4)"],["∫ from 0 to 1 of x dx","1/2"]]],
["🌊","Differential Equations","useful","A differential equation describes how something changes over time (growth, cooling, motion). Used in science and some advanced ML.","ODEs: first & second order · Systems · PDEs · Initial-value & boundary-value problems",[["Solve dy/dx = 2y with y(0) = 1","y = e^(2x)"],["Order of y'' + y = 0","2"]]],
["🖥️","Numerical & Applied Maths","core","Optimization finds the best answer, for example the lowest loss. Gradient descent is the core idea: w ← w − lr × gradient.","Numerical methods · Approximation · Numerical integration & differentiation · Mathematical modelling · Optimization · Operations research · Financial maths",[["w = 5, gradient = 4, lr = 0.5. New w?","5 − 0.5·4 = 3"],["Minimum of (x − 2)² + 1","1, at x = 2"],["Euler step: y' = y, y = 1, h = 0.1","y ≈ 1.1"]]]
];
const CONSTS=[["π","≈ 3.14159, circle ratio"],["e","≈ 2.71828, growth and logs"],["i","√−1, so i² = −1"],["φ","≈ 1.618, golden ratio"],["0","zero (adding it changes nothing)"],["1","identity (multiplying changes nothing)"]];
const SYM=[["≠","not equal"],["≤ ≥","less/greater or equal"],["√","square root"],["Σ","sum"],["∏","product"],["∞","infinity"],["≈","approximately"],["∝","proportional to"],["Δ","change"],["θ","angle"],["∫","integral"],["d/dx","derivative"],["∂","partial derivative"],["∇","gradient"],["∈","belongs to"],["⊂","subset"],["∴","therefore"]];